version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staging_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MssqlP@ssword1"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  etl-app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mssql:
        condition: service_started
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: staging_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      MSSQL_USER: sa
      MSSQL_PASSWORD: MssqlP@ssword1
      MSSQL_DB: master
      MSSQL_HOST: mssql
      MSSQL_PORT: 1433

      API_USERS_URL: https://jsonplaceholder.typicode.com/users
      API_POSTS_URL: https://jsonplaceholder.typicode.com/posts

volumes:
  pg_data:
  mssql_data:
